# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universit채t Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI f체r molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "Raptor"
SPDX-PackageDownloadLocation = "https://github.com/seqan/raptor/"

[[annotations]]
path = "cppcheck"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2006-2024, Knut Reinert & Freie Universit채t Berlin", "2016-2024, Knut Reinert & MPI f체r molekulare Genetik"]
SPDX-License-Identifier = "CC0-1.0"

